### PR TITLE
Fix The login sign up button on mobile screen

### PR DESCRIPTION
**Pull request by Ghost-67-G**
## Describe Your Changes
I Fix The login sign up button on mobile screen 

Please provide a summary of the changes you've made in the React JavaScript code for The Monkeys UI.

## Related Issue Ticket Number and Link
https://github.com/the-monkeys/the_monkeys/issues/107
#107

Please link the issue ticket number that this PR solves.

## React Component Checklist Before Requesting a Review
- [x ] I have performed a self-review of my code.
- [ x] I have checked for the responsiveness.
- [ x] Spelling and grammar are correct.
- [ x] Code consistency and style are checked.
- [ x] The changes have been tested and work as expected.
- [ x] All new and existing tests passed.
- [ x] The code is properly commented.

## Screenshots

image

If applicable, add screenshots to help explain your changes in the UI. Please ensure that the screenshots do not contain any sensitive information.

## Additional Information

Add any other context or information about the pull request here.

### CODE REVIEW

**Comment by sumitavachakraborty** [comment]
The ref an onclick methods are working fine, just change the login and signup buttons to side by side and decrease the font, it will look better.

**Comment by daveaugustus** [comment]
@Ghost-67-G please address the above comment by @sumitavachakraborty

**Comment by Ghost-67-G** [comment]
I am sorry for late response its my first time to contribute to open source. I am not a good designer. I just review this request and fix. I am unable to do design task. These more difficult. Sorry again

**Comment by daveaugustus** [comment]
@Ghost-67-G without approval of @sumitavachakraborty and @Rahullokare I won't be merging this PR.

**Pull request closed without merging**
