### PR TITLE
added the dependencies and changed the readme for the time being

### PR DESCRIPTION
**Pull request by sumitavachakraborty**
…pendencies accordingly

## Readme changes npm and material UI doesnt works perfectly with react 18.2.0, 
ref - https://github.com/mui/material-ui/issues/32142

## React Component Checklist Before Requesting a Review
- [ ] I have performed a self-review of my code.
- [ ] I have checked for the responsiveness.
- [ ] Spelling and grammar are correct.
- [ ] Code consistency and style are checked.
- [ ] The changes have been tested and work as expected.
- [x] All new and existing tests passed.
- [x] The code is properly commented.

Add any other context or information about the pull request here.

### CODE REVIEW

**Comment by Rahullokare** [comment]
It will not work like this; you also need to remove the instances where these libraries were imported and write appropriate code to eliminate the error.

**Comment by sumitavachakraborty** [comment]
Yes, also there are dependencies of izitoast.. as it also doesnot work with react 18.. so also have to remove that, but many sections are using izitoast.

**Comment by daveaugustus** [comment]
@sumitavachakraborty and @Rahullokare Should we close this PR?

**Comment by sumitavachakraborty** [comment]
@daveaugustus yes close this pr

**Pull request closed without merging**
